# Generated by Django 4.0.6 on 2022-07-15 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_account_user_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
